#!/usr/bin/env bash
# init-workspace.sh — populate the sandbox workspace volume (runs INSIDE the
# ticket container; scripts/run-ticket.sh pipes it in over stdin).
#
# Usage: bash -s -- <repo-url> <branch-name> [base-ref]
#
# Idempotent: a fresh volume gets a clone from GitHub; an existing workspace
# gets a fetch. The ticket branch is created from base-ref (default
# origin/main) or checked out if it already exists locally or on the remote.

set -euo pipefail

if [[ $# -lt 2 ]]; then
  echo "Usage: init-workspace.sh <repo-url> <branch-name> [base-ref]" >&2
  exit 1
fi

REPO_URL="$1"
BRANCH_NAME="$2"
BASE_REF="${3:-origin/main}"
WORKSPACE=/workspace

cd "${WORKSPACE}"

if [[ -d .git ]]; then
  echo "Workspace already cloned; fetching origin..."
  git fetch origin
else
  if [[ -n "$(ls -A . 2>/dev/null)" ]]; then
    echo "Error: ${WORKSPACE} is non-empty but not a git repository." >&2
    exit 1
  fi
  echo "Cloning ${REPO_URL} into ${WORKSPACE}..."
  git clone "${REPO_URL}" .
fi

if git show-ref --verify --quiet "refs/heads/${BRANCH_NAME}"; then
  echo "Checking out existing local branch ${BRANCH_NAME}"
  git checkout "${BRANCH_NAME}"
elif git show-ref --verify --quiet "refs/remotes/origin/${BRANCH_NAME}"; then
  echo "Checking out remote branch origin/${BRANCH_NAME}"
  git checkout -b "${BRANCH_NAME}" "origin/${BRANCH_NAME}"
else
  echo "Creating branch ${BRANCH_NAME} from ${BASE_REF}"
  git checkout -b "${BRANCH_NAME}" "${BASE_REF}"
fi

if git show-ref --verify --quiet "refs/remotes/origin/${BRANCH_NAME}"; then
  git branch --set-upstream-to="origin/${BRANCH_NAME}" "${BRANCH_NAME}" 2>/dev/null || true
fi

# Dev-only .env: copied from the committed sandbox template, never from the
# host. Fallback covers branches created before .env.sandbox was merged.
if [[ ! -f .env ]]; then
  if [[ -f .env.sandbox ]]; then
    cp .env.sandbox .env
    echo "Wrote .env from .env.sandbox template"
  else
    cat > .env <<'EOF'
# Generated by init-workspace.sh — dev-only sandbox values, no real secrets.
JWT_SECRET=ticket-dev-jwt-not-for-production
SEED_EMAIL=teacher@example.com
SEED_PASSWORD=changeme
SEED_NAME="Music Teacher"
FRONTEND_URL=http://localhost:3001
PUBLIC_API_URL=http://localhost:8081
EOF
    echo "Wrote .env with built-in sandbox defaults (.env.sandbox not in this branch)"
  fi
fi

echo "Sandbox workspace ready on branch ${BRANCH_NAME} ($(git rev-parse --short HEAD))"
